# Generated by Django 4.0.5 on 2022-06-16 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staff',
            name='salon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='salonservice',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_services', to='business_accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='salonservice',
            name='staff',
            field=models.ManyToManyField(blank=True, to='business_accounts.staff'),
        ),
        migrations.AddField(
            model_name='salonreview',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_reviews', to='business_accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='salonreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='records',
            name='businessaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='business_accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='records',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_accounts.salonservice'),
        ),
        migrations.AddField(
            model_name='records',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_accounts.staff'),
        ),
        migrations.AddField(
            model_name='records',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interior',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_accounts.businessaccount'),
        ),
        migrations.AddField(
            model_name='businessaccount',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
